version: '3.1'

services:

  drupal:
    image: drupal:8.3.6-apache
    ports:
      - 80:80
    restart: always

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: password
    restart: always
